/**
 * GitHub statistics for Greymass and WharfKit organizations
 * Generated by scripts/count-repos.sh
 */

export interface OrganizationStats {
  name: string;
  repositories: number;
  followers: number;
  activeRepos30d: number;
  url: string;
}

export interface GitHubStats {
  updated: string;
  organizations: {
    greymass: OrganizationStats;
    wharfkit: OrganizationStats;
  };
  totals: {
    repositories: number;
    followers: number;
    activeRepos30d: number;
  };
}

declare const github: GitHubStats;
export default github;
